task_manager: "test_managers.infinite_generation.InfiniteGenerationManager"
interactive: False
seed: 9487

# task specific configs
height: 8192
width: 8192
batch_size: 1
parallel_batch_size: 128
num_gen: 20
lowres_height: 128

