task_manager: "test_managers.infinite_generation.InfiniteGenerationManager"
interactive: False
seed: 9487

# task specific configs
height: 2048
width: 2048
batch_size: 1
parallel_batch_size: 4
num_gen: 20
lowres_height: 128

